### ISSUE TITLE
promote !!

### ISSUE THREAD

**Issue by jgirardet** [dssg/dickens#1]
I think you should talk about dickens here:

https://stackoverflow.com/questions/5189699/how-to-make-a-class-property
or here
https://stackoverflow.com/questions/128573/using-property-on-classmethods

very good idea anyway, thanks

**Comment by jesteria** [comment]
Sorry I missed this. Thanks!

Would you be interested?

**Comment by jgirardet** [comment]
In ?

**Comment by jgirardet** [comment]
done !

**Comment by jesteria** [comment]
:tada: thanks! :fireworks:
